// @ts-check

const POPULATION_MULTIPLIER = 10

export const RULE_SET = Object.freeze({
  id: 'microscope-ecology-v3',
  simulationHz: 60,
  maxCatchUpSteps: 5,
  world: Object.freeze({
    viewportSpanMultiplier: 6,
    viewportAreaMultiplier: 36,
    populationMultiplier: POPULATION_MULTIPLIER,
  }),
  gait: Object.freeze({
    reachEnd: 0.22,
    driveEnd: 0.46,
    catchEnd: 0.78,
  }),
  player: Object.freeze({
    initialMass: 36,
    startProtectionMs: 6000,
    gaitFrequency: 1.65,
    burstAcceleration: 2200,
    reachBrakePerSecond: 22,
    driveBrakePerSecond: 1.4,
    catchBrakePerSecond: 24,
    restBrakePerSecond: 32,
    lateralBurst: 145,
    maxSpeed: 240,
    deadZone: 10,
    joystickRadiusCssPx: 72,
  }),
  mass: Object.freeze({
    radiusScale: 4,
    cellAbsorbRatio: 1.12,
    contactDepthRatio: 0.74,
    nutrientEfficiency: 1,
    cellEfficiency: 0.28,
    maximum: 520,
    absorptionDurationSeconds: 0.72,
    absorptionPullPerSecond: 11,
  }),
  npc: Object.freeze({
    count: 54 * POPULATION_MULTIPLIER,
    reachBrakePerSecond: 15,
    driveBrakePerSecond: 1.8,
    catchBrakePerSecond: 18,
    restBrakePerSecond: 22,
    safeSpawnDistance: 330,
    archetypes: Object.freeze([
      Object.freeze({
        id: 'micrococcus',
        name: '미립구균',
        morph: 0,
        aggro: 'flee',
        aggroRadius: 300,
        locomotion: 'gait',
        massMin: 6,
        massMax: 20,
        gaitFrequency: 2.25,
        burstAcceleration: 1050,
        lateralBurst: 65,
        maxSpeed: 150,
        turnRate: 2.3,
      }),
      Object.freeze({
        id: 'ciliophoran',
        name: '섬모편모충',
        morph: 1,
        aggro: 'pursue',
        aggroRadius: 390,
        locomotion: 'gait',
        massMin: 28,
        massMax: 68,
        gaitFrequency: 1.75,
        burstAcceleration: 980,
        lateralBurst: 75,
        maxSpeed: 132,
        turnRate: 2,
      }),
      Object.freeze({
        id: 'larvoid',
        name: '다족유생충',
        morph: 2,
        aggro: 'passive',
        aggroRadius: 0,
        locomotion: 'constant',
        massMin: 20,
        massMax: 54,
        gaitFrequency: 3.2,
        burstAcceleration: 0,
        lateralBurst: 0,
        maxSpeed: 82,
        turnRate: 0.4,
      }),
      Object.freeze({
        id: 'tentacle-amoeba',
        name: '촉수아메바',
        morph: 3,
        aggro: 'pursue',
        aggroRadius: 480,
        locomotion: 'gait',
        massMin: 58,
        massMax: 150,
        gaitFrequency: 1,
        burstAcceleration: 720,
        lateralBurst: 40,
        maxSpeed: 92,
        turnRate: 1.1,
      }),
      Object.freeze({
        id: 'diplococcus',
        name: '쌍구균',
        morph: 4,
        aggro: 'passive',
        aggroRadius: 0,
        locomotion: 'drift',
        massMin: 14,
        massMax: 42,
        gaitFrequency: 0.42,
        burstAcceleration: 0,
        lateralBurst: 0,
        maxSpeed: 16,
        turnRate: 0.22,
      }),
    ]),
  }),
  nutrient: Object.freeze({
    targetCount: 320 * POPULATION_MULTIPLIER,
    mass: 1,
  }),
  rendering: Object.freeze({
    dprMaximum: 1.5,
    ambientParticles: 1800,
    internalParticlesPerCell: 4,
    trailCapacity: 640,
    trailLifetimeSeconds: 1.75,
  }),
})
