// @ts-check

export const RULE_SET = Object.freeze({
  id: 'microscope-field-v1',
  simulationHz: 60,
  maxCatchUpSteps: 5,
  world: Object.freeze({
    viewportSpanMultiplier: 6,
    viewportAreaMultiplier: 36,
  }),
  gait: Object.freeze({
    reachEnd: 0.22,
    driveEnd: 0.46,
    catchEnd: 0.78,
  }),
  player: Object.freeze({
    initialMass: 36,
    startProtectionMs: 6000,
    gaitFrequency: 1.65,
    burstAcceleration: 2200,
    reachBrakePerSecond: 22,
    driveBrakePerSecond: 1.4,
    catchBrakePerSecond: 24,
    restBrakePerSecond: 32,
    lateralBurst: 145,
    maxSpeed: 240,
    deadZone: 10,
    joystickRadiusCssPx: 72,
  }),
  mass: Object.freeze({
    radiusScale: 4,
    cellAbsorbRatio: 1.12,
    contactDepthRatio: 0.74,
    nutrientEfficiency: 1,
    cellEfficiency: 0.28,
    maximum: 520,
  }),
  npc: Object.freeze({
    count: 54,
    awarenessRadius: 430,
    gaitFrequency: 1.12,
    burstAcceleration: 720,
    reachBrakePerSecond: 15,
    driveBrakePerSecond: 1.8,
    catchBrakePerSecond: 18,
    restBrakePerSecond: 22,
    lateralBurst: 52,
    maxSpeed: 108,
    massMin: 14,
    massMax: 118,
    safeSpawnDistance: 330,
  }),
  nutrient: Object.freeze({
    targetCount: 320,
    massMin: 0.7,
    massMax: 1.45,
  }),
  rendering: Object.freeze({
    dprMaximum: 1.5,
    ambientParticles: 1800,
    internalParticlesPerCell: 8,
    trailCapacity: 640,
    trailLifetimeSeconds: 1.75,
  }),
})
