// @ts-check

const POPULATION_MULTIPLIER = 30

export const RULE_SET = Object.freeze({
  id: 'microscope-ecology-v4',
  simulationHz: 60,
  maxCatchUpSteps: 5,
  world: Object.freeze({
    viewportSpanMultiplier: 6,
    viewportAreaMultiplier: 36,
    populationMultiplier: POPULATION_MULTIPLIER,
  }),
  gait: Object.freeze({
    reachEnd: 0.22,
    driveEnd: 0.46,
    catchEnd: 0.78,
    catchTimeScale: 0.5,
    movementSpeedMultiplier: 2,
  }),
  player: Object.freeze({
    initialMass: 36,
    startProtectionMs: 6000,
    gaitFrequency: 1.65,
    burstAcceleration: 2200,
    reachBrakePerSecond: 22,
    driveBrakePerSecond: 1.4,
    catchBrakePerSecond: 24,
    restBrakePerSecond: 32,
    lateralBurst: 145,
    maxSpeed: 240,
    deadZone: 10,
    joystickRadiusCssPx: 72,
  }),
  mass: Object.freeze({
    radiusScale: 4,
    cellAbsorbRatio: 1.12,
    nutrientEfficiency: 1,
    cellEfficiency: 0.28,
    maximum: 520,
    absorptionDamageFractionPerSecond: 1.15,
    absorptionMinimumContactFactor: 0.12,
    absorptionMinimumMass: 0.05,
    absorptionPullPerSecond: 11,
  }),
  npc: Object.freeze({
    count: 54 * POPULATION_MULTIPLIER,
    reachBrakePerSecond: 15,
    driveBrakePerSecond: 1.8,
    catchBrakePerSecond: 18,
    restBrakePerSecond: 22,
    safeSpawnDistance: 330,
    decisionIntervalTicks: 6,
    spatialCellSize: 256,
    archetypes: Object.freeze([
      Object.freeze({
        id: 'micrococcus',
        name: '미립구균',
        morph: 0,
        aggro: 'flee',
        aggroRadius: 300,
        locomotion: 'gait',
        massMin: 6,
        massMax: 20,
        gaitFrequency: 2.25,
        burstAcceleration: 1050,
        lateralBurst: 65,
        maxSpeed: 150,
        turnRate: 2.3,
      }),
      Object.freeze({
        id: 'ciliophoran',
        name: '섬모편모충',
        morph: 1,
        aggro: 'pursue-player',
        aggroRadius: 390,
        locomotion: 'gait',
        massMin: 28,
        massMax: 68,
        gaitFrequency: 1.75,
        burstAcceleration: 980,
        lateralBurst: 75,
        maxSpeed: 132,
        turnRate: 2,
      }),
      Object.freeze({
        id: 'larvoid',
        name: '다족유생충',
        morph: 2,
        aggro: 'passive',
        aggroRadius: 0,
        locomotion: 'constant',
        massMin: 20,
        massMax: 54,
        gaitFrequency: 3.2,
        burstAcceleration: 0,
        lateralBurst: 0,
        maxSpeed: 82,
        turnRate: 0.4,
      }),
      Object.freeze({
        id: 'tentacle-amoeba',
        name: '촉수아메바',
        morph: 3,
        aggro: 'pursue-cell',
        aggroRadius: 480,
        locomotion: 'gait',
        massMin: 58,
        massMax: 150,
        gaitFrequency: 1,
        burstAcceleration: 720,
        lateralBurst: 40,
        maxSpeed: 92,
        turnRate: 1.1,
      }),
      Object.freeze({
        id: 'diplococcus',
        name: '쌍구균',
        morph: 4,
        aggro: 'passive',
        aggroRadius: 0,
        locomotion: 'drift',
        massMin: 14,
        massMax: 42,
        gaitFrequency: 0.42,
        burstAcceleration: 0,
        lateralBurst: 0,
        maxSpeed: 16,
        turnRate: 0.22,
      }),
      Object.freeze({
        id: 'streptococcus',
        name: '연쇄구균',
        morph: 5,
        aggro: 'pursue-cell',
        aggroRadius: 420,
        locomotion: 'gait',
        massMin: 16,
        massMax: 48,
        gaitFrequency: 1.4,
        burstAcceleration: 900,
        lateralBurst: 55,
        maxSpeed: 120,
        turnRate: 1.8,
      }),
      Object.freeze({
        id: 'spirillum',
        name: '나선편모충',
        morph: 6,
        aggro: 'flee',
        aggroRadius: 340,
        locomotion: 'gait',
        massMin: 8,
        massMax: 30,
        gaitFrequency: 2,
        burstAcceleration: 1000,
        lateralBurst: 70,
        maxSpeed: 140,
        turnRate: 2.4,
      }),
      Object.freeze({
        id: 'radiolarian',
        name: '방산포자충',
        morph: 7,
        aggro: 'pursue-cell',
        aggroRadius: 520,
        locomotion: 'gait',
        massMin: 72,
        massMax: 180,
        gaitFrequency: 0.85,
        burstAcceleration: 650,
        lateralBurst: 30,
        maxSpeed: 80,
        turnRate: 0.9,
      }),
    ]),
  }),
  nutrient: Object.freeze({
    targetCount: 320 * POPULATION_MULTIPLIER,
    massMin: 1,
    massMax: 6,
    collisionRadiusScale: 4.5,
    pointSizeBase: 5.5,
    pointSizeMassScale: 2.5,
  }),
  rendering: Object.freeze({
    dprMaximum: 1.5,
    ambientParticles: 1800,
    internalParticlesPerCell: 4,
    trailCapacity: 640,
    trailLifetimeSeconds: 1.75,
    cellPlaneOverscan: 1.35,
  }),
})
